name: Build images using Containerfile
on: [push]

jobs:
  build:
    name: Build client image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get timestamp
      id: get-timestamp
      run: echo "timestamp=$(date +%s)" >> $GITHUB_OUTPUT

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/roboticsoutreach/discord-bot:latest
          ghcr.io/roboticsoutreach/discord-bot:${{ github.sha }}
          ghcr.io/roboticsoutreach/discord-bot:latest-${{ steps.get-timestamp.outputs.timestamp }}
